MyVpvCF:
 Type: AWS::EC2::VPC
 Properties: 
   CidrBlock: 10.0.0.0/16
   EnableDnsHostnames: true
   EnableDnsSupport: true
   InstanceTenancy: default
   Tags:
     - Key: foo
       Value: bar

AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyVPC1:
    Type: 'AWS::EC2::VPC'
    Properties: 
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: 10.0.0.0/16
      
  sub1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC1
      CidrBlock: 10.0.0.0/24



===========
drmcgiftpx

Resources:
 MyVpvCF:
    Type: 'AWS::EC2::VPC'
    Properties: 
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
        CidrBlock: 10.0.0.0/16
        Tags:
            - Key: foo
              Value: bar
